### PR TITLE
Convert input fields into textareas

### PR DESCRIPTION
**Pull request by MarceloPedra**
This allow a better search and replace of longer HTML blocks.

### CODE REVIEW

**Comment by MarceloPedra** [comment]
Hello. Any point of view about this @bradt?

**Comment by MarceloPedra** [comment]
Hello. Any point of view about this @bradt, @mattgrshaw ?

**Comment by mattgrshaw** [comment]
Hi @MarceloPedra, sorry for the delay. We don't have any plans to change the text inputs over to text areas at this time.

**Comment by MarceloPedra** [comment]
ok, sorry to hear that.

Anyway, I'd like to ask: how would you recommend to proceed when one have to replace large text blocks with line breaks? The current input fields won't support that. The textareas worked well really great in my tests to handle replacement of strings with line breaks.

A good solution will be welcomed.
Best regards

**Pull request closed without merging**
