### PR TITLE
Free plugin reskin

### LINKED ISSUE #81: BSR lite plugin should have new UI
This is a continuation of the work started in https://github.com/deliciousbrains/better-search-replace-pro/pull/65 where @lewis-dbi and @mattgrshaw began implementing the new plugin UI.

As Matt mentioned in https://github.com/deliciousbrains/better-search-replace-pro/pull/65#issuecomment-1058763572, a branch for `ui-reskin` has been started already.

## Acceptance Criteria

- [x] The styles from the pro plugin have been carried over to the lite plugin.
- [x] The upgrade sidebar has been added to the UI.

### Dry Run Details Modal

- [x] An `Upgrade Now` tooltip is displayed when hovering over an item in the changes column.
- [x] The existing upgrade call to action below the dry run details table is removed, per [Brad's request in Figma](https://www.figma.com/file/qaw9KV6xS8V0sWnNF3d66H?node-id=242:1235#149703727).

### Upgrade Links

- [x] In the sidebar, the Upgrade Now `button` element is changed to an `a` element, which is the semantically correct element for a link that navigates off-site. The appearance should stay the same. This change should also resolve the incorrect behavior on the Help tab that Lewis described in https://github.com/deliciousbrains/better-search-replace/pull/80#issue-1159794347.

- [x] All upgrade links have been updated to the following URLs with UTM parameters. This URL was suggested by Brad in https://github.com/deliciousbrains/site/issues/3108#issuecomment-1060949121.
  - [x] Tooltips
    ```
    https://deliciousbrains.com/better-search-replace/upgrade/?utm_source=insideplugin&utm_medium=web&utm_content=tooltip&utm_campaign=bsr-to-migrate
    ```
  - [x] Header
    ```
    https://deliciousbrains.com/better-search-replace/upgrade/?utm_source=insideplugin&utm_medium=web&utm_content=header&utm_campaign=bsr-to-migrate
    ```
  - [x] Sidebar
    ```
    https://deliciousbrains.com/better-search-replace/upgrade/?utm_source=insideplugin&utm_medium=web&utm_content=sidebar&utm_campaign=bsr-to-migrate
    ```
  - [x] Help tab
    ```
    https://deliciousbrains.com/better-search-replace/upgrade/?utm_source=insideplugin&utm_medium=web&utm_content=help-tab&utm_campaign=bsr-to-migrate
    ```

### PR DESCRIPTION
**Pull request by lewis-dbi**
Resolves #81

@kevinwhoffman 

I have done everything barring the modal changes as I'm not sure how to make changes to the framework. It may be best to get one of the devs to add in the final changes there, but if not, I'm happy too if I can be pointed in the right direction.

The upsell buttons (both in the header and the sidebar) need wiring up when the upsell page is live. Currently, the sidebar upgrade button is behaving a little bit strange on the search/replace and help pages. For example, pressing it on the Help page downloads the system info txt file. I think its the way in which the button element is defined to perform a specific task when clicked, so that will need to be addressed.

The two things that still need wiring up on the modal are as follows:

- Add upgrade notice.
- Display tooltip when hovering over an item in the "Changes" column.

CleanShot 2022-03-04 at 15 56 05@2x

Thanks.

### CODE REVIEW

**Comment by mattgrshaw** [comment]
@kevinwhoffman @lewis-dbi I've added the tooltips to the results modal and updated the links as discussed in #81.

Please have a look and let me know if you have any changes.

**Review by kevinwhoffman — CHANGES_REQUESTED** [review]
@mattgrshaw Nice work. I've reviewed and left my requested changes below. Let's have @lewis-dbi do his review and then all changes can be addressed at once.

## Requested Changes

### Search/Replace Tab

- [x] The help icon next to Replace GUIDs is currently linked to an old page on the codex with no content. It should be pointed to the new page here:
  ```
  https://wordpress.org/support/article/changing-the-site-url/#important-guid-note
  ```

☝️ Let's make sure this link gets updated in the [pro version's PR](https://github.com/deliciousbrains/better-search-replace-pro/pull/65) as well.

### Modal

- [x] Links in the item column should be underlined so they appear more interactive.
- [x] Tooltip text should display:
  >  **UPGRADE** to view details on the exact changes that will be made

  Google Chrome-Better Search Replace ‹ bsr-lite — WordPress-20220318T131901

  Here is the WP Migrate Lite tooltip for reference. Let's mimic this exactly with the exception of the link color. The link color can stay as is.

  Google Chrome-100 Stage 0 of 1 - WP Migrate ‹ bsr-lite — WordPress-20220318T133230

## Sidebar

- [x] (1) Padding above the sidebar heading should be reduced. See [Figma mockup](https://www.figma.com/file/2Fhp0njqNlOcEKkB9g19Yr/free-plugin-sidebars?node-id=17%3A859) for reference.
- [x] (2) The first line of text in each list item should be vertically centered with the checkmark icon. The text is currently a little low.

sidebar-feedback

**Comment by kevinwhoffman** [comment]
@mattgrshaw @lewis-dbi I just pulled the latest changes. All looks good to me except for the tooltip text which is currently center-aligned and has one word hanging on the second line.

Google Chrome-Better Search Replace ‹ bsr-to-migrate — WordPress-20220407T030717

I think this CSS declaration is to blame for the centered alignment.

Google Chrome-Better Search Replace ‹ bsr-to-migrate — WordPress-20220407T031046

## Requested Change

- [ ] Text should be left-aligned and width of the tooltip should be constrained to about `220px` so that the two lines are roughly equal length. See below:

  Google Chrome-Better Search Replace ‹ bsr-to-migrate — WordPress-20220407T031657

**Comment by lewis-dbi** [comment]
Checked both plugins and can't spot anything new, @mattgrshaw.

Nice one.

**Pull request merged**
